Repository MyFormworks/Formworks, pull requests merged in 2020-09, with the labels that each got.

#2 PR Template Added
  .github/pull_request_template.md
Labels: dev-task

#7 Add glossary.md to docs
  docs/glossary.md
Labels: documentation, ui-components

#11 Feature/property wrapper
  Package.swift
  Sources/Formworks/Property Wrappers/ManualLayout.swift
  Tests/FormworksTests/Property Wrappers/ManualLayoutTests.swift
  Tests/FormworksTests/XCTestManifests.swift
  Tests/LinuxMain.swift
Labels: dev-task, domain

#26 Tools
  .github/workflows/swift.yml
  .swiftLint.yml
Labels: dev-task, domain, tools
