Repository MyFormworks/Formworks, pull requests merged in 2020-11, with the labels that each got.

#89 Feature/codable models
  README.md
  Resources/FormWorksStyleGuide_1.0.jpg
  Resources/FormWorksStyleGuide_1.1.jpg
  Resources/JSON.md
  Resources/glossary.md
  Sources/Formworks/Design System/FWStyleSpecification.swift
  Sources/Formworks/Extensions/UIColor+Extension.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentModel.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentModelWrapper.swift
  Sources/Formworks/FWComponents/FWComponent/FWDecodedComponentModel.swift
  Sources/Formworks/FWComponents/FWTextComponents/FWTextComponentView.swift
  Sources/Formworks/FWComponents/FWTextComponents/FWTextComponentViewModel.swift
  Sources/Formworks/FWComponents/FWTextComponents/FWTextModel.swift
  Sources/Formworks/FWForm/FWFormModel.swift
  Sources/Formworks/FWSnapshots/FWTextComponentSnapshot.swift
  Sources/Formworks/JSON Decoder/FWJSON.swift
  Sources/Formworks/Validators/FWRegexValidator.swift
  Tests/FormworksTests/TestFixtures.swift
  Tests/FormworksTests/Validators/FWRegexValidatorTests.swift
Labels: dev-task

#96 Add Multiline Text Component
  Sources/Formworks/Design System/TextComponentSpec.swift
  Sources/Formworks/Extensions/UIColor+Extension.swift
  Sources/Formworks/Extensions/UIFont+Extension.swift
  Sources/Formworks/Extensions/UIViewController+Extension.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentModel.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentModelWrapper.swift
  Sources/Formworks/FWComponents/FWFields/FWTextView.swift
  Sources/Formworks/FWComponents/FWMultilineComponent/FWMultilineComponentView.swift
  Sources/Formworks/FWComponents/FWMultilineComponent/FWMultilineComponentViewModel.swift
  Sources/Formworks/FWComponents/FWTextComponent/FWTextComponentView.swift
  Sources/Formworks/FWComponents/FWTextComponent/FWTextComponentViewModel.swift
  Sources/Formworks/FWComponents/FWTextComponent/FWTextModel.swift
  Sources/Formworks/FWForm/FWFormModel.swift
  Sources/Formworks/FWForm/FWFormViewController.swift
  Sources/Formworks/FWForm/FWFormViewModel/FWFormViewModel.swift
  Sources/Formworks/FWForm/FWFormViews/FWFormSubmitTableCell.swift
  Sources/Formworks/JSON Decoder/FWJSON.swift
  Sources/Formworks/Validators/FWRegexValidator.swift
  Sources/Formworks/Validators/FWValidator.swift
Labels: dev-task, domain, ui-components

#100 Fix Multiline and Multiline Validation Checkmark
  Sources/Formworks/FWComponents/FWMultilineComponent/FWMultilineComponentView.swift
  Sources/Formworks/FWComponents/FWMultilineComponent/FWMultilineComponentViewModel.swift
  Sources/Formworks/FWForm/FWFormViewController.swift
Labels: bug, dev-task

#104 Fix Snapshot, Keyboard Dismissal and NavBar Tint Color
  Sources/Formworks/Design System/FWStyleSpecification.swift
  Sources/Formworks/Design System/FormSpec.swift
  Sources/Formworks/Extensions/UIColor+Extension.swift
  Sources/Formworks/Extensions/UIFont+Extension.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentCell.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentModelWrapper.swift
  Sources/Formworks/FWComponents/FWComponent/FWComponentViewModel.swift
  Sources/Formworks/FWComponents/FWFields/FWLabel.swift
  Sources/Formworks/FWComponents/FWFields/FWTextField.swift
  Sources/Formworks/FWComponents/FWFields/FWTextView.swift
  Sources/Formworks/FWComponents/FWMultilineComponent/FWMultilineComponentView.swift
  Sources/Formworks/FWComponents/FWMultilineComponent/FWMultilineComponentViewModel.swift
  Sources/Formworks/FWComponents/FWTextComponent/FWTextComponentView.swift
  Sources/Formworks/FWComponents/FWTextComponent/FWTextComponentViewModel.swift
  Sources/Formworks/FWForm/FWFormViewController.swift
  Sources/Formworks/FWForm/FWFormViews/FWDismissHeader.swift
  Sources/Formworks/FWForm/FWFormViews/FWFormSubmitTableCell.swift
  Sources/Formworks/FWSnapshots/FWComponentSnapshot.swift
  Sources/Formworks/FWSnapshots/FWFormSnapshot.swift
  Sources/Formworks/FWSnapshots/FWTextComponentSnapshot.swift
  Sources/Formworks/Form Generation/FWConfiguration.swift
Labels: bug, documentation, ui-components

#103 Add animation to keyboard not cover textfield
  Sources/Formworks/Design System/ComponentSpec.swift
  Sources/Formworks/FWForm/FWFormViewController.swift
Labels: bug, dev-task, domain
